In [1]:
import pandas as pd 
import numpy as np

In [2]:
import bitstring

In [36]:
source_dir = '../data/disco_to_csv/'
dest_dir = '../data/proc/'
extension = '.csv'

In [3]:
# Complete event log
elog = pd.read_csv(source_dir.__add__('BPI Challenge 2018.csv'))

In [4]:
# Subprocesses/documents
control_summary = pd.read_csv(source_dir.__add__('Control summary.csv'))
dep_control = pd.read_csv(source_dir.__add__('Department control parcels.csv'))
entitle_app = pd.read_csv(source_dir.__add__('Entitlement application.csv'))
geo_parcel = pd.read_csv(source_dir.__add__('Geo parcel document.csv'))
inspec = pd.read_csv(source_dir.__add__('Inspection.csv'))
parcel_doc = pd.read_csv(source_dir.__add__('Parcel document.csv'))
pay_app = pd.read_csv(source_dir.__add__('Payment application.csv'))
ref_align = pd.read_csv(source_dir.__add__('Reference alignment.csv'))

In [5]:
all_subprocess = [control_summary, dep_control, entitle_app, geo_parcel, inspec, parcel_doc, pay_app, ref_align]
all_proc = all_subprocess + [elog]

In [6]:
for sp in all_proc:
    sp.loc[sp['Resource'] == '0;n/a', 'Resource'] = np.NaN

In [7]:
for sp in all_subprocess:
    sp['Case ID'] = sp['Case ID'].apply(lambda x: x if np.isnan(x) else bitstring.BitArray('int:64=%d' % x).hex)

In [8]:
for sp in all_proc:
    sp['docid'] = sp['docid'].apply(lambda x: x if np.isnan(x) else bitstring.BitArray('int:64=%d' % x).hex)
    sp['eventid'] = sp['eventid'].apply(lambda x: x if np.isnan(x) else bitstring.BitArray('int:64=%d' % x).hex)

In [9]:
elog.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,8b99873a6136cfa6,Payment application-Application-mail income,NaN,2015/05/08 00:00:00.000,Variant 1832,1832,960.35,NaN,NaN,NaN,...,False,mail income,mail income,ffc0054364e897d9,Payment application,NaN,complete,none,Application,True
1,8b99873a6136cfa6,Payment application-Application-mail valid,NaN,2015/05/08 00:00:00.000,Variant 1832,1832,960.35,NaN,NaN,NaN,...,False,mail valid,mail valid,ffc0054364e897d9,Payment application,NaN,complete,none,Application,True
2,8b99873a6136cfa6,Entitlement application-Main-mail valid,NaN,2015/05/08 00:00:00.000,Variant 1832,1832,960.35,NaN,NaN,NaN,...,False,mail valid,mail valid,ffc005428239d50b,Entitlement application,NaN,complete,none,Main,True

In [10]:
dep_control.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,fe80053f34cdb3f5,Department control parcels-Main-performed,727350,2015/09/15 19:31:11.000,Variant 1,1,960.35,NaN,NaN,NaN,...,False,performed,performed,fe80053f34cdb3f5,Department control parcels,fe80053f34cdb3f8,complete,none,Main,True
1,fe4005421a73f96a,Department control parcels-Main-performed,727350,2015/10/22 08:05:15.000,Variant 1,1,28192.23,NaN,NaN,NaN,...,False,performed,performed,fe4005421a73f96a,Department control parcels,fe4005421a73f96d,complete,none,Main,True
2,fe80054350543512,Department control parcels-Main-performed,fb5fa8,2015/11/05 11:58:40.000,Variant 1,1,6684.43,NaN,NaN,NaN,...,False,performed,performed,fe80054350543512,Department control parcels,fe80054350543515,complete,none,Main,True

In [11]:
entitle_app.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,ffc005428239d50b,Entitlement application-Main-mail valid,NaN,2015/05/08 00:00:00.000,Variant 5,5,960.35,NaN,NaN,NaN,...,False,mail valid,mail valid,ffc005428239d50b,Entitlement application,NaN,complete,none,Main,True
1,ffc005428239d50b,Entitlement application-Main-mail valid,NaN,2015/05/08 00:00:00.000,Variant 5,5,960.35,NaN,NaN,NaN,...,False,mail valid,mail valid,ffc005428239d50b,Entitlement application,NaN,complete,none,Main,True
2,ffc005428239d50b,Entitlement application-Main-initialize,Document processing automaton,2015/10/26 13:27:10.390,Variant 5,5,960.35,NaN,NaN,NaN,...,False,initialize,initialize,ffc005428239d50b,Entitlement application,ffc005428239d50a,complete,none,Main,True

In [12]:
geo_parcel.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,ffc00555e0372f63,Geo parcel document-Main-initialize,Document processing automaton,2016/06/22 15:51:03.862,Variant 7,7,20652.65,NaN,NaN,NaN,...,False,initialize,initialize,ffc00555e0372f63,Geo parcel document,ffc00555e0372f65,complete,none,Main,True
1,ffc00555e0372f63,Geo parcel document-Declared-begin editing,Document processing automaton,2016/06/22 15:51:03.869,Variant 7,7,20652.65,NaN,NaN,NaN,...,False,begin editing,begin editing,ffc00555e0372f63,Geo parcel document,ffc00555e03733a9,complete,none,Declared,True
2,ffc00555e0372f63,Geo parcel document-Declared-finish editing,Document processing automaton,2016/06/22 15:51:04.929,Variant 7,7,20652.65,NaN,NaN,NaN,...,False,finish editing,finish editing,ffc00555e0372f63,Geo parcel document,ffc00555e03733dd,complete,none,Declared,True

In [13]:
inspec.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,fe800539d0e93da7,Inspection-Remote-plan,Inspection automaton,2015/07/10 15:59:06.364,Variant 61,61,1191.87,NaN,NaN,NaN,...,False,plan,plan,fe800539d0e93da7,Inspection,fe800539d0e93daa,complete,none,Remote,True
1,fe800539d0e93da7,Inspection-Remote-initialize,Inspection automaton,2015/07/10 15:59:06.364,Variant 61,61,1191.87,NaN,NaN,NaN,...,False,initialize,initialize,fe800539d0e93da7,Inspection,fe800539d0e93da9,complete,none,Remote,True
2,fe800539d0e93da7,Inspection-Remote-save,Inspection automaton,2015/07/10 15:59:06.398,Variant 61,61,1191.87,NaN,NaN,NaN,...,False,save,save,fe800539d0e93da7,Inspection,fe800539d0e93db1,complete,none,Remote,True

In [14]:
parcel_doc.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,ff000537695e5fe8,Parcel document-Main-initialize,fb5fa8,2015/06/10 11:16:28.000,Variant 698,698,960.35,NaN,NaN,NaN,...,False,initialize,initialize,ff000537695e5fe8,Parcel document,ff000537695e5feb,complete,none,Main,True
1,ff000537695e5fe8,Parcel document-Main-begin editing,dde669,2015/06/15 13:01:05.000,Variant 698,698,960.35,NaN,NaN,NaN,...,False,begin editing,begin editing,ff000537695e5fe8,Parcel document,ff000537d0074092,complete,none,Main,True
2,ff000537695e5fe8,Parcel document-Main-save,dde669,2015/06/15 13:01:25.000,Variant 698,698,960.35,NaN,NaN,NaN,...,False,save,save,ff000537695e5fe8,Parcel document,ff000537d00740a0,complete,none,Main,True

In [15]:
pay_app.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,ffc0054364e897d9,Payment application-Application-mail income,NaN,2015/05/08 00:00:00.000,Variant 8,8,960.35,NaN,NaN,NaN,...,False,mail income,mail income,ffc0054364e897d9,Payment application,NaN,complete,none,Application,True
1,ffc0054364e897d9,Payment application-Application-mail valid,NaN,2015/05/08 00:00:00.000,Variant 8,8,960.35,NaN,NaN,NaN,...,False,mail valid,mail valid,ffc0054364e897d9,Payment application,NaN,complete,none,Application,True
2,ffc0054364e897d9,Payment application-Application-initialize,Document processing automaton,2015/11/06 11:21:27.376,Variant 8,8,960.35,NaN,NaN,NaN,...,False,initialize,initialize,ffc0054364e897d9,Payment application,ffc0054364e897d8,complete,none,Application,True

In [16]:
ref_align.head(3)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,(case) amount_applied0,(case) amount_applied1,(case) amount_applied2,(case) amount_applied3,...,(case) young farmer,activity,concept:name,docid,doctype,eventid,lifecycle:transition,note,subprocess,success
0,ff40053afe8ce5ea,Reference alignment-Main-initialize,Reference alignment processor,2015/07/24 21:10:08.000,Variant 1,1,960.35,NaN,NaN,NaN,...,False,initialize,initialize,ff40053afe8ce5ea,Reference alignment,ff40053afe8ce5ed,complete,none,Main,True
1,ff40053afe8ce5ea,Reference alignment-Main-performed,Reference alignment processor,2015/07/24 21:10:08.000,Variant 1,1,960.35,NaN,NaN,NaN,...,False,performed,performed,ff40053afe8ce5ea,Reference alignment,ff40053afe8ce5f5,complete,none,Main,True
2,ff40053afe90bbc4,Reference alignment-Main-initialize,Reference alignment processor,2015/07/24 21:22:19.000,Variant 2,2,28192.23,NaN,NaN,NaN,...,False,initialize,initialize,ff40053afe90bbc4,Reference alignment,ff40053afe90bbc9,complete,none,Main,True

In [17]:
 # ref_align['Case ID'] = ref_align['Case ID'].apply(lambda x: bitstring.BitArray('int:64=%d' % x).hex)

In [18]:
# bitstring.BitArray('int:64=54037444591557142').hex

In [ ]:
# write back to csv files for further analysis/usage in other tools
for df in all_proc:
    df_name =  [k for k,v in locals().items() if df.equals(v)][0].__add__(extension) # file_name = var name + file extension
    df.to_csv(dest_dir.__add__(df_name), index=False)